active_hospital: hospital3
hospitals:
  hospital3:
    adapter: hospital3_adapter
    his:
      type: webservice
      url: http://192.0.19.141:1506/services/WSInterface?wsdl
      call_operator: WF_YY
      certificate: "bnjlQ7s0A2H2qk7M+XsT8GJ1TIreeK9O"
      server_name: GetResiVisitRecord
    name: 厦大附一
sqlite:
  path: ../backend/database.db
sync:
  interval: 300
