# -*- mode: python ; coding: utf-8 -*-
# Windows 7 兼容版本打包配置

block_cipher = None

a = Analysis(
    ['simple_web_server.py'],
    pathex=[],
    binaries=[
        ('D:\\workpath\\python3.7.9\\lib\\site-packages\\bcrypt\\_bcrypt.pyd', 'bcrypt'),
    ],
    datas=[
        ('database.db', '.'),
        ('main.py', '.'),
        ('main_static.py', '.'),
        ('database.py', '.'),
        ('security.py', '.'),
        ('models', 'models'),
        ('routers', 'routers'),
    ],
    hiddenimports=[
        # 核心模块 - 必须先导入主模块
        'uvicorn',
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.http.h11_impl',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.protocols.websockets.wsproto_impl',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'uvicorn.config',
        'uvicorn.main',
        'uvicorn.server',
        'uvicorn.supervisors',
        'uvicorn.supervisors.statreload',
        # FastAPI 和 Starlette
        'fastapi',
        'fastapi.applications',
        'fastapi.routing',
        'fastapi.middleware',
        'fastapi.middleware.cors',
        'fastapi.security',
        'fastapi.security.oauth2',
        'fastapi.security.utils',
        'fastapi.staticfiles',
        'fastapi.responses',
        'starlette',
        'starlette.applications',
        'starlette.routing',
        'starlette.middleware',
        'starlette.staticfiles',
        'starlette.responses',
        'starlette.requests',
        'starlette.background',
        'starlette.datastructures',
        # SQLModel 和 SQLAlchemy
        'sqlmodel',
        'sqlalchemy',
        'sqlalchemy.ext',
        'sqlalchemy.ext.declarative',
        'sqlalchemy.orm',
        'sqlalchemy.sql',
        'sqlalchemy.sql.default_comparator',
        'sqlalchemy.pool',
        'sqlalchemy.engine',
        # Pydantic
        'pydantic',
        'pydantic.fields',
        'pydantic.main',
        'pydantic.types',
        'pydantic.validators',
        # 认证相关（包含 bcrypt 和 passlib 以兼容旧密码）
        'jose',
        'jose.jwt',
        'jose.exceptions',
        'jose.constants',
        'passlib',
        'passlib.context',
        'passlib.hash',
        'bcrypt',
        '_bcrypt',
        # 加密相关
        'cryptography',
        'cryptography.fernet',
        'cryptography.hazmat',
        'cryptography.hazmat.primitives',
        'cryptography.hazmat.primitives.hashes',
        'cryptography.hazmat.primitives.serialization',
        'cryptography.hazmat.backends',
        'cryptography.hazmat.backends.openssl',
        # 异步和文件操作
        'aiofiles',
        'anyio',
        'h11',
        'httptools',
        'websockets',
        'wsproto',
        'click',
        # 标准库
        'webbrowser',
        'threading',
        'datetime',
        'typing',
        'email',
        'email.mime',
        'multipart',
        'hashlib',
        'base64',
        'secrets',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='backend_server',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,  # 禁用 UPX 压缩，提高兼容性
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    # Windows 7 兼容性设置
    manifest=None,
    icon=None,
)
