# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['simple_web_server.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('database.db', '.'),
        ('main.py', '.'),
        ('main_static.py', '.'),
        ('database.py', '.'),
        ('security.py', '.'),
        ('models', 'models'),
        ('routers', 'routers'),
    ],
    hiddenimports=[
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'passlib.handlers.bcrypt',
        'passlib.context',
        'passlib.hash',
        'passlib.utils',
        'sqlalchemy.sql.default_comparator',
        'webbrowser',
        'threading',
        'fastapi',
        'fastapi.middleware.cors',
        'fastapi.security',
        'fastapi.security.oauth2',
        'fastapi.security.utils',
        'fastapi.staticfiles',
        'fastapi.responses',
        'sqlmodel',
        'pydantic',
        'jose',
        'jose.jwt',
        'jose.exceptions',
        'jose.constants',
        'datetime',
        'typing',
        'bcrypt',
        'cryptography',
        'cryptography.fernet',
        'cryptography.hazmat',
        'cryptography.hazmat.primitives',
        'cryptography.hazmat.primitives.hashes',
        'cryptography.hazmat.primitives.serialization',
        'starlette.staticfiles',
        'starlette.responses',
        'aiofiles',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='backend_server',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)